### PR TITLE
Fixed null pointer. (gcc7 compilation errors)

### PR DESCRIPTION
**Pull request by kkulczak**
I was having same error as given in the topic https://unix.stackexchange.com/questions/444874/problem-with-torcs-installation-error-with-openal

This pull  request should fix it

### CODE REVIEW

**Comment by fmirus** [comment]
@Magikis thanks for pointing this out. However, this fix results in a build error when using gcc5 (which has worked for me ever since :slightly_smiling_face:). Is there a way of fixing this for both versions?

**Comment by kkulczak** [comment]
Uups. No, I don't have any idea how to keep backwards compatiblity. :(

**Comment by deltaflyer** [comment]
Hello @Magikis 

I filed a PR with the requested backward compatibility https://github.com/fmirus/torcs-1.3.7/pull/6

**Comment by fmirus** [comment]
superseded by #6

**Pull request closed without merging**
